apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: invalid-tekton-task-gcb
spec:
  steps:
    - name: echo
      image: alpine
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      script: |
        #!/bin/sh
        echo "Hello world"
