apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: invalid-gcb-task
spec:
  params:
    - name: platform
    - name: browser
  matrix:
    params:
      - name: platform
        value:
          - linux
          - mac
          - windows
      - name: browser
        value:
          - chrome
          - safari
          - firefox
  steps:
    - name: echo
      image: alpine
      script: |
        echo "$(params.platform) and $(params.browser)"
