apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: invalid-tekton-task
spec:
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "Hello $(params.IDONOTEXIST)"
