apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: invalid-tekton-pipeline
spec:
  params:
    - name: username
      type: string
  tasks:
    - name: hello
      taskSpec:
        steps:
          - image: ubuntu
            script: echo "Hello $(params.IDONOTEXIST)"
