apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "tekton.webhook.config"
webhooks:
  - name: "tekton.webhook.config"
    rules:
      - apiGroups: ["tekton.dev"]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pipelines", "tasks"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: tekton-webhook
        path: /validate
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVWi9GNnN2dit5K2lJWDRNa2ZqNG9QYkJjT2ZVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSXpNVEV5TVRJeU1URXlPRm9YRFRJek1USXlNVEl5TVRFeU9Gb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXY3VkwvZFNNcDZKM0FrNXE0TVVVSE5EV29LaC9yMDVhWDE2Rwp1UlVyZWltNjlrV1ZKU2VzRTV0OFRCdldZVnQwSTFkMVJmTG1UTkRMdmlka3lHSTd5bEZzNFRpNW1pcDQxN2JaCnRTdmQrR01xajdyYkhCR21VK1EzV0hPN0JSYnlTdGR4ZHBqZkh1MzZ1MTd5K2hMSXpYS1FVMW84TTRyVUxXemkKU0RxdVdlT0RGaVg0L2JkemtybXZPSktlUTNjL0hFRzkxNDNxZHYyK1NFNkVRVXJXREQ5RWlxdTJCS2J1aGdidAp2eGJjNFpvY1BpY2R1YzNGYlZrWW1uUGNmckVXazNNaEZ4RE1STUhEL2EzN2VUamxtd2c2aG5XOHNUU1JmMEpYClZUd0xRdkx4YUc0VVZwQWdGSVBJNlJmWDNJYTdpbTZIcjd0akZMdTRaUUpzSGozQWVRSURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVZGJDVjRmOVNXWHhWcWlPLzcwNEI1QktaMThVd0h3WURWUjBqQkJnd0ZvQVVkYkNWNGY5UwpXWHhWcWlPLzcwNEI1QktaMThVd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFGcTlMaUlxTWJTSEhoWjRlck1PajNWUnoyT2xuMmtBTU1jWVpTSDdIVG55VVdVdTcwVXVOb3o5dHg2eEIKSW5HUGFTUG8vMlNVdXM3NzYyWHdDWGZsRmxtYWd3Rk4vZVZsL04vYkZKN0tUMU4rMlgvTEd4a2Fxa2RqRHVaUQptZytETnNWS2Vzdm5uczh4RlQ0NUV6OUpRM2dXU1BXSGovMHhnUi8yR01zRW03ZkN3K1RwMjdlcFBjL29NbHlrCmhmR2p2TVR3MVNndEhQOFE3ZDdzdHZFNXEyOXlUL0dUbUxpb2QvQTBNVGRlanpGYVpOdEsxaGphZ1Y1LzZsdnIKeDlUTDZkbWh5SjZtcXVsd01CM3JjbE8wN3pyWERTcXdaeFloZnlrOVNPeGlBcExzN3lFaFI1eTI5cTdKZG5PaQozRm9YeWc3U1pOWEFEOEtTdENBOWd2cVVEdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
